version: '3.5'

services:
  manager:
    image: ipmdev/autoddos_manager
    build: ./manager
    networks:
      - private
    deploy:
      placement:
        constraints: [node.role == manager]

  runner:
    image: ipmdev/autoddos_runner
    build: ./runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    environment:
      - MANAGER_URL=ws://manager:7071/v1/runner
    networks:
      - private
    depends_on:
      - manager
    deploy:
      mode: global
      # placement:
      #   constraints: [node.role == worker]

networks:
  private:
