version: '3.5'

services:
  runner:
    image: ipmdev/autoddos_runner
    build: ./runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - runner
    deploy:
      mode: global
      placement:
        constraints: [node.role == worker]

  manager:
    image: ipmdev/autoddos_manager
    build: ./manager
    networks:
      - runner
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  runner:
